# LECTURE 1:  A very simple NN (input to output)

Seeing what is happening during feedforeward within a fully connected layer.

$$z_j = \sum_{k} w_{jk} * y_k^{in} + b_j$$

$$y_{j}^{out} = f(z_{j})$$

where:
* $j$ is the output index and $k$ is the inpout index
* $w_{jk}$ is the weight matrix
* $y_k^{in}$ is the input vector (neuron)
* $y_{j}^{out}$ is the output vector (neuron)
* $b_j$ is the bias vector

In [2]:
import numpy as np

In [3]:
N_in = 3 # input layer size
N_out = 2 # output layer size

w = np.random.uniform(low = -1, high = 1, size = (N_out, N_in)) # random weights
b = np.random.uniform(low = -1, high = 1, size = N_out) # random biases : N_out vector

In [ ]:
y_in = np.array([0.2, 0.4, -0.1]) # input vector

In [ ]:
z = np.dot(w, y_in) + b # result: the z vector of length N_out
y_out = 1/(1 + np.exp(-z)) # sigmoid activation function (applied element-wise )

In [6]:
print("Input:\n", y_in)
print("Output after activation (y_out):\n", y_out)

print("Weights:\n", w)
print("Biases:\n", b)
print("Pre-activation (z):\n", z)

Input:
 [ 0.2  0.4 -0.1]
Output after activation (y_out):
 [0.53031715 0.61818701]
Weights:
 [[-0.92372962  0.18871367  0.91210246]
 [ 0.52160159 -0.54131305 -0.84025871]]
Biases:
 [0.32188825 0.51003911]
Pre-activation (z):
 [0.12141755 0.48186008]


To visualize a neural network look at the lecture.

To also visualize multi layer networks look at the lecture